### ISSUE TITLE
Hold to record & release to send _ Voice not send/save until lock button press 

### ISSUE THREAD

**Issue by RzTutul** [fuadmostafij6/social_media_audio_recorder#1]
I want to send voice messages when the user holds the long press and release like what's app. but it will not work until it holds the long press and lock.  how can I resolve this?

**Comment by fuadmostafij6** [comment]
okay I will update my package soon

**Comment by fuadmostafij6** [comment]
> Okay I will update my package soon

**Comment by fuadmostafij6** [comment]
> I want to send voice messages when the user holds the long press and release like what's app. but it will not work until it holds the long press and lock. how can I resolve this?

Please use update version and check new parameter releaseToSend

                 RecordButton(
                      color: Colors.black,
                      allTextColor: Colors.white,
                       controller: controller!,
                      arrowColor: Colors.white,
                       releaseToSend: false,
                    onRecordEnd: (String value) {
                     setState(() {
                      filepath = value;
                     });
                  },
                  onRecordStart: () {
                
                  },
                  onCancelRecord: () {
               
                  },
                ),

**Comment by RzTutul** [comment]
**Thank you . I like your package**

**Comment by fuadmostafij6** [comment]
> **Thank you . I like your package**

Then can close this issue?
